// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.23.3
// source: app/if/app_sample_if.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrintRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Welcome string `protobuf:"bytes,1,opt,name=welcome,proto3" json:"welcome,omitempty"`
}

func (x *PrintRequest) Reset() {
	*x = PrintRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_if_app_sample_if_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintRequest) ProtoMessage() {}

func (x *PrintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_if_app_sample_if_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintRequest.ProtoReflect.Descriptor instead.
func (*PrintRequest) Descriptor() ([]byte, []int) {
	return file_app_if_app_sample_if_proto_rawDescGZIP(), []int{0}
}

func (x *PrintRequest) GetWelcome() string {
	if x != nil {
		return x.Welcome
	}
	return ""
}

type PrintResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *PrintResponse) Reset() {
	*x = PrintResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_if_app_sample_if_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintResponse) ProtoMessage() {}

func (x *PrintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_if_app_sample_if_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintResponse.ProtoReflect.Descriptor instead.
func (*PrintResponse) Descriptor() ([]byte, []int) {
	return file_app_if_app_sample_if_proto_rawDescGZIP(), []int{1}
}

func (x *PrintResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_app_if_app_sample_if_proto protoreflect.FileDescriptor

var file_app_if_app_sample_if_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x70, 0x2f, 0x69, 0x66, 0x2f, 0x61, 0x70, 0x70, 0x5f, 0x73, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x5f, 0x69, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x68,
	0x6f, 0x70, 0x64, 0x65, 0x76, 0x22, 0x28, 0x0a, 0x0c, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x22,
	0x27, 0x0a, 0x0d, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_if_app_sample_if_proto_rawDescOnce sync.Once
	file_app_if_app_sample_if_proto_rawDescData = file_app_if_app_sample_if_proto_rawDesc
)

func file_app_if_app_sample_if_proto_rawDescGZIP() []byte {
	file_app_if_app_sample_if_proto_rawDescOnce.Do(func() {
		file_app_if_app_sample_if_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_if_app_sample_if_proto_rawDescData)
	})
	return file_app_if_app_sample_if_proto_rawDescData
}

var file_app_if_app_sample_if_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_if_app_sample_if_proto_goTypes = []any{
	(*PrintRequest)(nil),  // 0: shopdev.PrintRequest
	(*PrintResponse)(nil), // 1: shopdev.PrintResponse
}
var file_app_if_app_sample_if_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_if_app_sample_if_proto_init() }
func file_app_if_app_sample_if_proto_init() {
	if File_app_if_app_sample_if_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_if_app_sample_if_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PrintRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_if_app_sample_if_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*PrintResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_if_app_sample_if_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_if_app_sample_if_proto_goTypes,
		DependencyIndexes: file_app_if_app_sample_if_proto_depIdxs,
		MessageInfos:      file_app_if_app_sample_if_proto_msgTypes,
	}.Build()
	File_app_if_app_sample_if_proto = out.File
	file_app_if_app_sample_if_proto_rawDesc = nil
	file_app_if_app_sample_if_proto_goTypes = nil
	file_app_if_app_sample_if_proto_depIdxs = nil
}
